name: debug repo-config workflow

on:
  pull_request:

jobs:
  repo-config:
    uses: defenseunicorns/delivery-github-actions-workflows/.github/workflows/repo-config.yml@ci/repo-config-implementation
    secrets:
      APPLICATION_ID: ${{ secrets.NARWHAL_BOT_APP_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.NARWHAL_BOT_SECRET }}
