# If the workflow trigger is "pull_request", run pre-commit checks.
name: pre-commit

on:
  pull_request:

permissions:
  pull-requests: write
  id-token: write
  contents: read

jobs:

  get-app-token:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.get-workflow-token.outputs.token }}
    steps:
    - name: Get Token
      id: get-workflow-token
      uses: peter-murray/workflow-application-token-action@v2
      with:
        application_id:  ${{ secrets.NARWHAL_BOT_APP_ID }}
        application_private_key:  ${{ secrets.NARWHAL_BOT_SECRET }}

  debug:
    needs: get-app-token
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2

  echo:
    needs: get-app-token
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.get-app-token.outputs.token }}

  pre-commit:
    needs: get-app-token
    uses: defenseunicorns/delivery-github-actions-workflows/.github/workflows/pre-commit.yml@ci/app_token_wip
    secrets:
      token: ${{ needs.get-app-token.outputs.token }}
    with:
      check-types: '["common", "terraform", "golang"]'
