# On every push to main, run release-please to automatically handle the release process.

name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:

  get-workflow-token:
    uses: defenseunicorns/delivery-github-actions-workflows/.github/workflows/get-workflow-token.yml@main
    secrets:
      APPLICATION_ID: ${{ secrets.NARWHAL_BOT_APP_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.NARWHAL_BOT_SECRET }}

  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ needs.get-workflow-token.outputs.token }}
          command: manifest
