name: test
on:
  repository_dispatch:
    types: [test-command]

permissions:
  id-token: write
  contents: read

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

jobs:

  get-workflow-token:
    uses: defenseunicorns/delivery-github-actions-workflows/.github/workflows/get-workflow-token.yml@main
    secrets:
      APPLICATION_ID: ${{ secrets.NARWHAL_BOT_APP_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.NARWHAL_BOT_SECRET }}

  e2e-test:
    uses: defenseunicorns/delivery-github-actions-workflows/.github/workflows/e2e-test.yml@main
    secrets:
      token: ${{ needs.get-workflow-token.outputs.token }}
      AWS_COMMERCIAL_ROLE_TO_ASSUME: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
      AWS_GOVCLOUD_ROLE_TO_ASSUME: ${{ secrets.AWS_GOVCLOUD_ROLE_TO_ASSUME }}
