name: test
on:
  repository_dispatch:
    types: [test-command]

permissions:
  id-token: write
  contents: read

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

jobs:

  # Parse the command, so we can decide which tests to run. Examples: "/test all", "/test validate", "/test e2e"
  # We can do as many of these as we want to get as granular as we want.
  parse:
    runs-on: ubuntu-latest
    outputs:
      run-e2e-commercial-insecure: ${{ steps.parse.outputs.run-e2e-commercial-insecure }}
    steps:
      - name: Parse Args
        id: parse
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/parse-test@main

  # Update the comment that triggered the /test command to show the run url
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Update Comment
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/comment@main
        with:
          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}

  e2e-commercial-insecure:
    if: needs.parse.outputs.run-e2e-commercial-insecure == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: e2e-commercial-insecure
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/e2e@main
        with:
          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
          region: us-east-2
          role-to-assume: ${{ secrets.NARWHAL_AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          github-context: "test / e2e-commercial-insecure"
          test-to-run: "insecure"
